
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1Ea3dOVEUzTXpJMU0xb1hEVE15TURrd01qRTNNekkxTTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTjNRCkRSRUZXRmo0c3BGZXBLckpJbGR0c2RCM0dxV2JtMlQvVjVpUmhzOGNPamdNdTZ4TWMvekhpU2dLRVIyOHVaSVkKZS9CUWRTS0pWMlp4TWhrY3pnUEhqZC9IMWppaXNSaDNCV0FEN1R4M3ozN3FyaHBqcjZvMmJ1SHR6ZVBtTTVTcApJK2NnblZBc0hpS0dRNWl6djQ3SjJKbWRzMk1EUUZqeHdkc2lsV3ozK1JOTmZJMDlIRm85bExCS0pYT1FVOVVqCm1UeUtucGk4a0F2dE9OTHF0eDlhMFBpdDVFVWVwbmRYRWtpaVlXSnAvencwTzA4dGQ1Sm1TOHNOOXZTMXA3TFoKQlBINHBHYW1YbkU0aExVbVNCUFdoKytVQ2Z2R3FwVEtTY1F5TG5wcTJFR1Z6SDJxeXdBN1MvNXdNNDJzUGluOAovWllYc2NUSXFsNzhpREwrZHFrQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZEUkZQcyt1SjRKczh2ZzFqU2pOdklxNTNHbExNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQXdEblhCWlJqSjhmL1hwN2VkVQo2dy9Fb0Nacm1ZeDFYSWs2RldYOWYzWDJvQVVadFVZNnFLZVRwRG1zekNwYVpwZ1dQajNTV3I4UGI3QzZCenJJCkdtbWk2SmhpRy9tSmk3c3pWczNTbkk0ZzRJSDIzS1l2ajdPWThyUU4wZGVxb2haYklHUHcrb2hMWmt5SnVqdEMKdDF5Zis5cEloeHZzMnE1Q3RlLy9nTzFqMUJESEROZTl1akZTR0FMWDYvUE9iWjQ1S01RWDU4d3FQamhzeStURgpUYmllVGlMN0hocytpTGxyYU1lVHRncG5GbEpETlh0alVXdkZUSzRjaWNYblJlUHUzZ09pRmpwekg5Y3paS3o2CjRpNFFsdE9YUWZUaWFGN3FaRXFtNFNHRHFITXltNC9NM05NTnRrc0l5b0VIRWd0VmI0YzZLbmd5d2syUEpFZWgKOUxzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://a295a4c4-7998-4f03-aefd-00ed340588bd.us-southeast-1.linodelke.net:443
  name: lke71402

users:
- name: lke71402-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ilc3T0FaeVNfX1pyY0NFUXc3T044b0FFU1k2aUhzaXJIOWdPVWxDR0RLSXcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tOHJreGYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiODY4ZmI2NWMtNDFmZC00NmVlLWFhMDItNjgyNmQwMDNlYmMwIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.BYQhqedQ1Plt8s2R8-c0F1yb67sdQXYEbHFK-crWy9zuUMYUQ9Fgn8-loB8uDpGWP5XC4Zvji-aOJYDWrK5k19u4EvYlCLwjhAELtRxDjp0C-C0OAJ7mXJfcw7rcdgU3xrFI5R7EBszWpWh122J7lShk5hemyt9dJLyFYetw1AVrPxLDGAKSzqYUfn0jA9KewJgMf-oOtCjUZ2vHqodZugSu3QpjstJeub-Krr4fBV3OpsgKPzXtZ6Dfeo7_dOYhQbEQMGv8ZqBT8QDz1mWEyy_rzxCAsvswYZvFBT8_mNID1M2EOB1zSadK5kJ-2i-nxe9JHmzA0hOviy7yT4tI4A

contexts:
- context:
    cluster: lke71402
    namespace: default
    user: lke71402-admin
  name: lke71402-ctx

current-context: lke71402-ctx
