appName: servicename
appImage: gcr.io/google-samples/microservices-demo/servicename
appVersion: v0.2.3
appReplicas: 1
containerPort: 8080
containerEnvVars:
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"
- name: DISABLE_DEBUGGER
  value: "1"

serviceType: ClusterIP
servicePort: 8080